"""empty message

Revision ID: 0125a5eae2c5
Revises: 4f2a94fb8f82
Create Date: 2022-03-25 15:52:30.794153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0125a5eae2c5'
down_revision = '4f2a94fb8f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marca', 'name')
    op.drop_column('tipo', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('marca', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
