"""empty message

Revision ID: 1294f8446de3
Revises: 65323e757531
Create Date: 2022-04-20 17:45:16.507438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1294f8446de3'
down_revision = '65323e757531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_license_key', 'user', type_='unique')
    op.drop_constraint('user_phonenumber_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_phonenumber_key', 'user', ['phonenumber'])
    op.create_unique_constraint('user_license_key', 'user', ['license'])
    # ### end Alembic commands ###
