"""empty message

Revision ID: 12dd3160ef2d
Revises: 
Create Date: 2022-03-25 18:58:13.420921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dd3160ef2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('phonenumber', sa.String(length=120), nullable=False),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('adress', sa.String(length=120), nullable=False),
    sa.Column('birthdate', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license'),
    sa.UniqueConstraint('phonenumber')
    )
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo1', sa.String(length=120), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('tipo1', sa.String(length=120), nullable=False),
    sa.Column('priceday', sa.Integer(), nullable=False),
    sa.Column('priceweek', sa.Integer(), nullable=False),
    sa.Column('discount1', sa.Integer(), nullable=True),
    sa.Column('discount2', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('provincia', sa.String(length=300), nullable=False),
    sa.Column('ciudad', sa.String(length=300), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=False),
    sa.Column('latitud', sa.Integer(), nullable=False),
    sa.Column('longitud', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'latitud', 'longitud')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moto')
    op.drop_table('modelo')
    op.drop_table('user')
    op.drop_table('tipo')
    op.drop_table('marca')
    # ### end Alembic commands ###
