"""empty message

Revision ID: 1a5ebd6e8e49
Revises: 12dd3160ef2d
Create Date: 2022-03-25 19:06:36.176920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5ebd6e8e49'
down_revision = '12dd3160ef2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('discount_week', sa.Integer(), nullable=True))
    op.add_column('moto', sa.Column('discount_weekend', sa.Integer(), nullable=True))
    op.add_column('moto', sa.Column('modelo_id', sa.Integer(), nullable=False))
    op.add_column('moto', sa.Column('tipo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'moto', 'modelo', ['modelo_id'], ['id'])
    op.create_foreign_key(None, 'moto', 'tipo', ['tipo_id'], ['id'])
    op.drop_column('moto', 'discount1')
    op.drop_column('moto', 'tipo1')
    op.drop_column('moto', 'modelo1')
    op.drop_column('moto', 'discount2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('discount2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('moto', sa.Column('modelo1', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('moto', sa.Column('tipo1', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('moto', sa.Column('discount1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'moto', type_='foreignkey')
    op.drop_constraint(None, 'moto', type_='foreignkey')
    op.drop_column('moto', 'tipo_id')
    op.drop_column('moto', 'modelo_id')
    op.drop_column('moto', 'discount_weekend')
    op.drop_column('moto', 'discount_week')
    # ### end Alembic commands ###
