"""empty message

Revision ID: 1be96ccd9e63
Revises: 2b5d0062b5c3
Create Date: 2022-03-25 19:27:42.086660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be96ccd9e63'
down_revision = '2b5d0062b5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fechanacimiento', sa.DateTime(), nullable=False))
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('user', 'fechanacimiento')
    # ### end Alembic commands ###
