"""empty message

Revision ID: 2b5d0062b5c3
Revises: 1a5ebd6e8e49
Create Date: 2022-03-25 19:09:34.838552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5d0062b5c3'
down_revision = '1a5ebd6e8e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moto', 'comment',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.drop_column('moto', 'brand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('brand', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('moto', 'comment',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
