"""empty message

Revision ID: 4f2a94fb8f82
Revises: 3e55f5ea7018
Create Date: 2022-03-25 15:48:22.134764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2a94fb8f82'
down_revision = '3e55f5ea7018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phonenumber', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['phonenumber'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phonenumber')
    # ### end Alembic commands ###
