"""empty message

Revision ID: 540401020bf5
Revises: d72f85b667a3
Create Date: 2022-03-25 14:48:54.897033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540401020bf5'
down_revision = 'd72f85b667a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('tipo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'moto', 'tipo', ['tipo_id'], ['id'])
    
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'license')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'adress')
    op.drop_column('user', 'PhoneNumber')
    op.drop_constraint(None, 'moto', type_='foreignkey')
    op.drop_column('moto', 'tipo_id')
    # ### end Alembic commands ###
