"""empty message

Revision ID: 9905fef6423c
Revises: 0125a5eae2c5
Create Date: 2022-03-25 15:53:09.745207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9905fef6423c'
down_revision = '0125a5eae2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marca', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('tipo', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


#def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
