"""empty message

Revision ID: b3a9bc9e51f1
Revises: 8a7890233771
Create Date: 2022-04-25 15:58:07.839895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a9bc9e51f1'
down_revision = '8a7890233771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('email', sa.String(), nullable=True))
    op.add_column('moto', sa.Column('telefono', sa.String(), nullable=True))
    op.drop_column('moto', 'latitud')
    op.drop_column('moto', 'longitud')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('longitud', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('moto', sa.Column('latitud', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('moto', 'telefono')
    op.drop_column('moto', 'email')
    # ### end Alembic commands ###
