"""empty message

Revision ID: ca385f4c02aa
Revises: f9d55e2ab4e0
Create Date: 2022-05-13 15:29:01.004808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca385f4c02aa'
down_revision = 'f9d55e2ab4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moto', 'provincia',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('moto', 'ciudad',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moto', 'ciudad',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('moto', 'provincia',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
