"""empty message

Revision ID: d72f85b667a3
Revises: d84d36ccf2a2
Create Date: 2022-03-25 14:26:01.418182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72f85b667a3'
down_revision = 'd84d36ccf2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.add_column('moto', sa.Column('modelo1', sa.String(length=120), nullable=False))
    op.add_column('moto', sa.Column('tipo1', sa.String(length=120), nullable=False))
    op.drop_constraint('moto_modelo_key', 'moto', type_='unique')
    op.drop_column('moto', 'modelo')
    op.drop_column('moto', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('tipo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('moto', sa.Column('modelo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('moto_modelo_key', 'moto', ['modelo'])
    op.drop_column('moto', 'tipo1')
    op.drop_column('moto', 'modelo1')
    op.drop_table('tipo')
    op.drop_table('marca')
    # ### end Alembic commands ###
