"""empty message

Revision ID: d84d36ccf2a2
Revises: 688abf9be264
Create Date: 2022-03-24 14:47:47.234610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84d36ccf2a2'
down_revision = '688abf9be264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('marca_id', sa.String(length=120), nullable=False),
    sa.Column('Moto_modelo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Moto_modelo'], ['moto.modelo'], ),
    sa.PrimaryKeyConstraint('id', 'name', 'marca_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelo')
    # ### end Alembic commands ###
