"""empty message

Revision ID: d8a41e4eb952
Revises: 0d12f06f58b2
Create Date: 2022-03-31 15:04:18.244667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a41e4eb952'
down_revision = '0d12f06f58b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moto', 'direccion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('direccion', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
