"""empty message

Revision ID: eaf3236147a9
Revises: 1294f8446de3
Create Date: 2022-04-20 22:21:31.537315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf3236147a9'
down_revision = '1294f8446de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('image_url', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moto', 'image_url')
    # ### end Alembic commands ###
